apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
