apiVersion: v1
kind: Service
metadata:
  name: gateway-app
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    app: gateway-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
